from __future__ import annotations
from dataclasses import replace
from openlongtail.configs.openlongtail_vace import GEO_HEAD_DIM, GEO_PROJECTION_TEMPERATURE, GRAPH_GATE_INIT_BIAS, OPENLONGTAIL_1P3B_CONFIG
REGISTER_STYLE_AXIS_NAMES: tuple[str, ...] = ('location', 'time_of_day', 'weather')
REGISTER_STYLE_AXIS_CARDINALITIES: tuple[int, ...] = (6, 4, 5)
REGISTER_STYLE_UNKNOWN_INDICES: tuple[int, ...] = tuple((c - 1 for c in REGISTER_STYLE_AXIS_CARDINALITIES))
REGISTER_STYLE_NUM_REGISTERS: int = 16
REGISTER_CAPTION_DIM: int = 4096
REGISTER_STYLE_REAR_ONLY: bool = True
REGISTER_STYLE_REAR_TARGET_VIEWS: tuple[int, ...] = (3, 4, 5)
REGISTER_GRAPH_CONDITIONS: dict[int, tuple[int, int, int]] = {1: (0, 2, 0), 2: (0, 1, 0), 3: (0, 1, 2), 4: (0, 1, 2), 5: (0, 1, 2)}
REGISTER_GRAPH_AVAILABLE: dict[int, tuple[int, int, int]] = {1: (1, 1, 0), 2: (1, 1, 0), 3: (1, 1, 1), 4: (1, 1, 1), 5: (1, 1, 1)}
REGISTER_STYLE_DROPOUT_PROB: float = 0.15
REGISTER_REAR_WARP_DROPOUT_MAX: float = 0.3
REGISTER_REAR_WARP_DROPOUT_WARMUP: int = 8000
REGISTER_STYLE_REAR_LOSS_WEIGHT: float = 1.0
REGISTER_LAMBDA_CYC_MAX: float = 0.5
REGISTER_LAMBDA_CYC_WARMUP: int = 2000
REGISTER_CYCLE_SIGMA_SKIP: float = 0.7
REGISTER_CYCLE_REAR_WEIGHT: float = 1.0
REGISTER_CYCLE_CROSS_WEIGHT: float = 0.25
REGISTER_FLOW_LOWFREQ_POOL: int = 4
REGISTER_VISIBILITY_THRESHOLD: float = 0.5
REGISTER_ANTI_SALIENCY_START: int = 12000
REGISTER_LAMBDA_SAL: float = 0.05
REGISTER_ANTI_SALIENCY_CENTER_SIGMA: float = 0.35
REGISTER_STAGE1_END: int = 2000
REGISTER_STAGE2_END: int = 12000
REGISTER_NEW_MODULE_LR_CAP: float = 1e-05
REGISTER_LORA_LR_CAP: float = 1e-05
REGISTER_GRAD_CLIP_CAP: float = 0.5
REGISTER_FLOW_SHIFT: float = 3.0
REGISTER_WARMUP_STEPS: int = 500
OPENLONGTAIL_REGISTER_1P3B_CONFIG = replace(OPENLONGTAIL_1P3B_CONFIG, optim=replace(OPENLONGTAIL_1P3B_CONFIG.optim, new_module_lr=REGISTER_NEW_MODULE_LR_CAP, lora_lr=REGISTER_LORA_LR_CAP, grad_clip=REGISTER_GRAD_CLIP_CAP, warmup_steps=REGISTER_WARMUP_STEPS), model=replace(OPENLONGTAIL_1P3B_CONFIG.model, sigma_shift=REGISTER_FLOW_SHIFT, sample_shift=REGISTER_FLOW_SHIFT), run=replace(OPENLONGTAIL_1P3B_CONFIG.run, train_log_name='train_log_register_1p3b.jsonl'))
__all__ = ['OPENLONGTAIL_REGISTER_1P3B_CONFIG', 'REGISTER_STYLE_AXIS_NAMES', 'REGISTER_STYLE_AXIS_CARDINALITIES', 'REGISTER_STYLE_UNKNOWN_INDICES', 'REGISTER_STYLE_NUM_REGISTERS', 'REGISTER_CAPTION_DIM', 'REGISTER_STYLE_REAR_ONLY', 'REGISTER_STYLE_REAR_TARGET_VIEWS', 'REGISTER_GRAPH_CONDITIONS', 'REGISTER_GRAPH_AVAILABLE', 'REGISTER_STYLE_DROPOUT_PROB', 'REGISTER_REAR_WARP_DROPOUT_MAX', 'REGISTER_REAR_WARP_DROPOUT_WARMUP', 'REGISTER_STYLE_REAR_LOSS_WEIGHT', 'REGISTER_LAMBDA_CYC_MAX', 'REGISTER_LAMBDA_CYC_WARMUP', 'REGISTER_CYCLE_SIGMA_SKIP', 'REGISTER_CYCLE_REAR_WEIGHT', 'REGISTER_CYCLE_CROSS_WEIGHT', 'REGISTER_FLOW_LOWFREQ_POOL', 'REGISTER_VISIBILITY_THRESHOLD', 'REGISTER_ANTI_SALIENCY_START', 'REGISTER_LAMBDA_SAL', 'REGISTER_ANTI_SALIENCY_CENTER_SIGMA', 'REGISTER_STAGE1_END', 'REGISTER_STAGE2_END', 'REGISTER_NEW_MODULE_LR_CAP', 'REGISTER_LORA_LR_CAP', 'REGISTER_GRAD_CLIP_CAP', 'REGISTER_FLOW_SHIFT', 'REGISTER_WARMUP_STEPS', 'GRAPH_GATE_INIT_BIAS', 'GEO_HEAD_DIM', 'GEO_PROJECTION_TEMPERATURE']
