from __future__ import annotations
from dataclasses import replace
from openlongtail.configs.openlongtail_vace import GEO_HEAD_DIM, GEO_PROJECTION_TEMPERATURE, GRAPH_GATE_INIT_BIAS, OPENLONGTAIL_1P3B_CONFIG
STYLE_AXIS_NAMES: tuple[str, ...] = ('road_environment', 'time_of_day', 'weather')
STYLE_AXIS_CARDINALITIES: tuple[int, ...] = (5, 4, 6)
STYLE_UNKNOWN_INDICES: tuple[int, ...] = tuple((c - 1 for c in STYLE_AXIS_CARDINALITIES))
STYLE_EMBED_DIM: int = 128
STYLE_REAR_ONLY: bool = True
STYLE_REAR_TARGET_VIEWS: tuple[int, ...] = (3, 4, 5)
STYLE_DROPOUT_PROB: float = 0.15
REAR_WARP_DROPOUT_MAX: float = 0.7
REAR_WARP_DROPOUT_WARMUP: int = 8000
STYLE_REAR_LOSS_WEIGHT: float = 1.5
OPENLONGTAIL_STYLE_1P3B_CONFIG = replace(OPENLONGTAIL_1P3B_CONFIG, run=replace(OPENLONGTAIL_1P3B_CONFIG.run, train_log_name='train_log_style_1p3b.jsonl'))
__all__ = ['OPENLONGTAIL_STYLE_1P3B_CONFIG', 'STYLE_AXIS_NAMES', 'STYLE_AXIS_CARDINALITIES', 'STYLE_UNKNOWN_INDICES', 'STYLE_EMBED_DIM', 'STYLE_REAR_ONLY', 'STYLE_REAR_TARGET_VIEWS', 'STYLE_DROPOUT_PROB', 'REAR_WARP_DROPOUT_MAX', 'REAR_WARP_DROPOUT_WARMUP', 'STYLE_REAR_LOSS_WEIGHT', 'GRAPH_GATE_INIT_BIAS', 'GEO_HEAD_DIM', 'GEO_PROJECTION_TEMPERATURE']
